name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '52 4 */2 * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.ZSDPOV_TOKEN }}
          owner: 2dust
          base: main
          head: main
